### ISSUE TITLE
Assertion `GTK_IS_WIDGET (conf_widget)' failed

### ISSUE THREAD

**Issue by afrancoto** [afrancoto/WebMenu#15]
I didn't know how to call the config window from the "Options" menu item, so i used another function (manage_window()). 
To have the last one opened with a click on the 'Preferences' button in Rhythmbox's Plugin window I wrote this shit: XD

<pre>
    def do_create_configure_widget(self):
         return self.manage_window(Gtk.Widget)
</pre>

I get this error: 

<pre>
(rhythmbox:23006): libpeas-CRITICAL **: show_configure_cb: assertion `GTK_IS_WIDGET (conf_widget)' failed
</pre>

**Comment by asermax** [comment]
That error occurs because 'do_create_configure_widget' is called by Peas (the plugin engine used by Gnome applications) expecting to get a widget in return, which it after stuffs into a dialog and presents to the user. 
What you are actually doing in your code, is call a subrutine that opens the manage window, and returns a None to Peas. Your window IS shown (since your code creates and shows the whole window), but it's not managed by peas (you can keep clicking on the 'Preferences' button and new windows keep comming up xD)

**Comment by afrancoto** [comment]
Mmm.. I see... I can change the manage function in something that returns a widget with everything in it, and then make another function that puts it inside a window when it is called by the "Options" menu item... 
unless you know how to call directly the Peas window that receive its content from the do_create_configure_widget, because I have no idea :P

**Comment by afrancoto** [comment]
And I also need to set the Peas window default size! :/

**Comment by afrancoto** [comment]
http://developer.gnome.org/libpeas/1.4/PeasGtkPluginManager.html

**Comment by asermax** [comment]
Nupe, no idea. 
I think the easiest way is what you proposed, divide the manage_window method in two parts :3
Try returning the widget and see how the dialog behaves... If it's smaller from what you want, I think you can set the width and height of the ScrollWindow.
Here: http://developer.gnome.org/gtk3/3.2/GtkScrolledWindow.html#gtk-scrolled-window-set-min-content-width

**Comment by afrancoto** [comment]
Fixed! :D
