### ISSUE TITLE
LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

### ISSUE THREAD

**Issue by afrancoto** [afrancoto/WebMenu#16]
This code in the draw_menu function:

<pre>
   os.system("echo draw_menu: "+ str(not menu_not_drawn))
    if not menu_not_drawn :
    ui_manager.remove_ui(ui_id) #Delete a previous drawn menu
    del ui_id
    ui_manager.ensure_update()
    os.system("echo \"it's him!\"")
</pre>

gives me this warning:

<pre>
draw_menu: True

(rhythmbox:7799): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
it's him!
</pre>

**Comment by afrancoto** [comment]
The warning is generated with the line

<pre>
ui_manager.ensure_update()
</pre>

**Comment by asermax** [comment]
I don't get this warning for some reason :S since the latest updates, it have been working fine with me, except for some flickers in the activating/disabling services (i'm testing it out, I'll probably post an issue later).

Btw, just a pair of offtopic points:
- To print debug info on screen, I recommend you use the print function as in any other python application. For default, rhythmbox doesn't show this info, but you can enable a whole application debug running it from console with the -d option ('rhythmbox -d') or, if you want the debug info from a particular module, using '-D module_name' ( e.g. 'rhythmbox -D WebMenu' ).
- Sorry I having been posting this last days, I got busy with some stuff and also wanted to finish the implementation of the fingerprinter extension in my lastfm_extension plugin. I have been checking on your progress, but haden't much to add to it, sorry!

**Comment by afrancoto** [comment]
You mean that some checkboxes don't work? It's because the URL that they are enabling is empty and I didn't know how to remove the relative checkbox from the treeview :P

Thanks! I saw that the print function didn't work and I was too lazy to google it! XD 

No problems! I'm in a rush because I don't know how much time I will have in the near future, so I try to do everything I can now, don't worry :P

**Comment by asermax** [comment]
Ok, I won't worry, but I'll see if I can help with something xD

And besides from the checkbox without URL, what have been happening is that if I enable/disable multiple services before clicking on 'Ok', sometimes it behaves correctly, others it enables/disables just some of the options I changed. It's weird, but it doesn't always happen, so I'm trying to figure it what makes it happen.

**Comment by afrancoto** [comment]
Now I remember: I got the same error! I clicked on "reset to default" and it never shown up again :/
